- name: Automatizacion de servidores
  hosts: servidores
  become: yes

  tasks:

    - name: Actulizar Paquetes APT
      apt:
        update_cache: yes

    - name: Crear Usuario ITLA
      user:
        name: itla
        state: present

    - name: Crear Carpeta "app"
      file:
        path: /home/ansible/app
        state: directory

    - name: Crear Archivo "hola.txt"
      copy:
        dest: /home/ansible/app/hola.txt
        content: "Hola desde Ansible"

    - name: Instalar Paquetes
      apt:
        name:
          - cowsay
          - htop
        state: present